import { FaRegSmile } from "react-icons/fa";
import { TbVirus } from "react-icons/tb";
import { RiVoiceprintLine } from "react-icons/ri";
import { BiBot, BiBrain, BiImageAlt, BiUserCircle } from "react-icons/bi";

export const slideData = [
	{
		id: 1,
		title: "Blockchain Technology",
		desc: "A blockchain is a type of distributed database or ledger—one of today's top tech trends—which means the power to update a blockchain is distributed between the nodes, or participants, of a public or private computer network.",
		vdo: "/assets/block.mp4",
	},
	{
		id: 2,
		title: "IoT",
		desc: "The Internet of Things (IoT) describes the network of physical objects—“things”—that are embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices and systems over the internet.",
		vdo: "/assets/IOT.mp4",
	},
	{
		id: 3,
		title: "NLP",
		desc: "Natural language processing (NLP) refers to the branch of computer science—and more specifically, the branch of artificial intelligence or AI—concerned with giving computers the ability to understand text and spoken words in much the same way human beings can.",
		vdo: "/assets/particle-bg.mp4",
	},
];

export const exploreCard = [
	{
		id: 1,
		name: "Solution",
		desc: " Convenient online services for  health, education, and more. User-friendly, scalable, and accessible from anywhere with an internet connection.",
		img: "/assets/research2.png",
		path: "/solutions",
	},

	{
		id: 3,
		name: "Research ",
		desc: "Expert research services to provide valuable insights and inform data-driven decision making. Thorough, accurate, and actionable results.",
		img: "/assets/product.png",
		path: "/research",
	},
];

export const startedData = [
	{
		id: 1,
		title: "Community",
		subTitle: "Explore",
		desc: "Connect with like-minded people in the community",
		step1: "Read our documentation",
		step2: "Explore the roadmap",
		step3: "Explore the code libraries",
		step4: "Learn with tutorials",
		btnName: "START ENGAGING",
	},
	{
		id: 2,
		title: "Developer",
		subTitle: "Develop",
		desc: "Start building innovative solutions with IOTA",
		step1: "Read our documentation",
		step2: "Explore the roadmap",
		step3: "Explore the code libraries",
		step4: "Learn with tutorials",
		btnName: "START DEVELOPING",
	},
	{
		id: 3,
		title: "Enterprise",
		subTitle: "Solutions",
		desc: "Discover new applications and business models",
		step1: "AuthBrain technologies",
		step2: "Explore industries",
		step3: "Partner with us",
		btnName: "START INNOVATING",
	},
];

export const industriesData = [
	{
		id: 1,
		title: "Natural Language Processing",
		feat1: "Chatbot",
		feat1Icon: <BiBot />,
		feat1Desc:
			"Chatbots use natural language processing (NLP) technology to understand and interpret user requests.",
		feat2: "Sentiment Analysis",
		feat2Icon: <FaRegSmile />,
		feat2Desc:
			"Sentiment analysis is a natural language processing (NLP) technique that involves using machine learning algorithms to extract subjective information from text data.",
		feat3: "Spam Recognition",
		feat3Icon: <BiUserCircle />,
		feat3Desc:
			"Spam Detection is detecting unsolicited and unwanted emails, we can prevent spam messages from creeping into the user's inbox, thereby improving user experience.",
		video: "/assets/banner-video.mp4",
	},
	{
		id: 2,
		title: "Computer Vision",
		feat1: "Image Processing",
		feat1Icon: <BiImageAlt />,
		feat1Desc:
			"Image processing is a subfield of artificial intelligence that focuses on the analysis and manipulation of digital images using computer algorithms.",
		feat2: "Disease Classification ",
		feat2Icon: <TbVirus />,
		feat2Desc:
			"It use machine learning algorithms and statistical models to automatically classify medical conditions based on various symptoms and patient history.",
		feat3: "Traffic Monitoring",
		feat3Icon: <BiUserCircle />,
		feat3Desc:
			" It accepts the video from a file or a camera, marks the moving vehicles with rectangles, and counts them.",
		video: "/assets/banner-video.mp4",
	},
	{
		id: 3,
		title: "Speech/ Signal Recognition",
		feat1: "Voice Recognition",
		feat1Icon: <RiVoiceprintLine />,
		feat1Desc:
			"Voice recognition, also known as speech recognition, is the ability of a computer or machine to recognize and interpret spoken language or commands.",
		feat2: "Brain Signal Recognition",
		feat2Icon: <BiBrain />,
		feat2Desc:
			"Brain signal recognition is a subfield of artificial intelligence that focuses on the analysis and interpretation of electroencephalography (EEG) signals generated by the human brain.",
		feat3: "Human AR",
		feat3Icon: <BiUserCircle />,
		feat3Desc:
			" Human Activity Recognition is the art of identifying and naming activities using AI from the gathered activity raw data by utilizing various sources . ",
		video: "/assets/banner-video.mp4",
	},
];

export const productsData = [
	{
		id: 1,
		name: "DiabTest",
		category: "Deep Learning",
		title:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur .",
		img: "/assets/research2.png",
		Featimg: "/assets/Banner.png",
	},
	{
		id: 2,
		name: "DiabTest2",
		category: "Deep Learning",
		title:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur .",
		img: "/assets/product.png",
		Featimg: "/assets/Banner.png",
	},
	{
		id: 3,
		name: "DiabTest3",
		category: "Deep Learning",
		title:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur .",
		img: "/assets/research2.png",
		Featimg: "/assets/Banner.png",
	},
	{
		id: 4,
		name: "DiabTest4",
		category: "Deep Learning",
		title:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur .",
		img: "/assets/research2.png",
		Featimg: "/assets/Banner.png",
	},
	{
		id: 5,
		name: "DiabTest5",
		category: "Deep Learning",
		title:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur .",
		img: "/assets/product.png",
		Featimg: "/assets/Banner.png",
	},
	{
		id: 6,
		name: "DiabTest6",
		category: "Deep Learning",
		title:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eveniet consequuntur .",
		img: "/assets/research2.png",
		Featimg: "/assets/Banner.png",
	},
];

export const teamMember = [
	{
		id: 1,
		name: "Md. Mehedi Hasan",
		designation: "CEO",
		img: "/assets/team/mehedi_hasan_CEO.jpg",
		linkedIn: "#",
		github: "#",
	},
	{
		id: 2,
		name: "Jarif Huda Angon",
		designation: "CTO",
		img: "/assets/team/Jarif-Huda-Angon.png",
		linkedIn: "#",
		github: "#",
	},
	{
		id: 3,
		name: "Asaf Ud Dulla",
		designation: "CMO",
		img: "/assets/team/asaf-kakon.jpg",
		linkedIn: "#",
		github: "#",
	},
	/* {
		id: 4,
		name: "Md. Mehedi Hasan",
		designation: "CEO",
		img: "/assets/team/mehedi_hasan_CEO.jpg",
		linkedIn: "#",
		github: "#",
	},
	{
		id: 5,
		name: "Jarif Huda Angon",
		designation: "CTO",
		img: "/assets/team/Jarif-Huda-Angon.png",
		linkedIn: "#",
		github: "#",
	},
	{
		id: 6,
		name: "Asaf Ud Dulla",
		designation: "CMO",
		img: "/assets/team/asaf-kakon.jpg",
		linkedIn: "#",
		github: "#",
	}, */
];
