import Head from "next/head";
import Banner from "../components/Homepage/Banner";
import Introduc from "../components/Homepage/Introduc";
import Industries from "../components/Homepage/Industries";
import Lightpaper from "../components/Homepage/Lightpaper";
import Explore from "../components/Homepage/Explore";
import GetStarted from "../components/Homepage/GetStarted";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Auth Brain | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<Banner />
				<Introduc />
				<Industries />
				<Lightpaper />
				<GetStarted />
				<Explore />
			</div>
		</div>
	);
}
